server:
  port: 8080
spring:
  application:
    name: service-gateway
  redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: host_route
          uri: lb://service-auth-authentication
          predicates:
            - Path=/oauth/*
        - id: host_route
          uri: lb://service-product
          predicates:
            - Path=/product/*
        - id: host_route
          uri: lb://service-user
          predicates:
            - Path=/user/*
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true