server:
  port: 8513
spring:
  application:
    name: auth-resource-service
  datasource:
    url: jdbc:mysql://localhost:3306/cmiracle-spring-cloud
    username: root
    password: Root!123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      min-idle: 10
      max-wait: 18000
      max-active: 200

jwt:
  signkey: 2WAsbgZrWPO9qIOl71VhHhAZIh2Pzxv4
  isskey: 5WB1gEXa6H35lGskhVscT9urE3cqx1pS

pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
mapper:
  not-empty: false
  identity: MYSQL
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false